version: '3'

services:
  poll:
    build: poll
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    networks:
      - poll-tier
    depends_on:
      - db
    restart: always
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - back-tier
      - poll-tier
    restart: always
  worker:
    build: worker
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=poll_db
      - POSTGRES_USER=poll_user
      - POSTGRES_PASSWORD=poll_password
    networks:
      - back-tier
    depends_on:
      - redis
      - db
    restart: always
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=poll_db
      - POSTGRES_USER=poll_user
      - POSTGRES_PASSWORD=poll_password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier
      - result-tier
    restart: always
  result:
    build: result
    ports:
      - "5001:80"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=poll_db
      - POSTGRES_USER=poll_user
      - POSTGRES_PASSWORD=poll_password
    networks:
      - result-tier
    depends_on:
      - db
    restart: always
networks:
  poll-tier:
  result-tier:
  back-tier:
volumes:
  db-data:
