#!/usr/bin/env python3

import math
import sys

a = sys.argv[1]
b = []
b = [ord(char) for char in a]

def main(a, b):
    side_length = math.ceil(math.sqrt(len(b)))
    matrix = [b[i:i+side_length] for i in range(0, len(b), side_length)]
    last_row_length = len(matrix[-1])
    if last_row_length < side_length:
        matrix[-1] += [0] * (side_length - last_row_length)
    formatted_matrix = ", ".join(["(" + ", ".join(map(str, row)) + ")" for row in matrix])
    print(f"matrix: ({formatted_matrix})")

if __name__ == "__main__":
    main(a, b)