#!/usr/bin/env python3

import math
import sys

a = sys.argv[1]
b = []
b = [ord(char) for char in a]

def transpose(formatted_matrix, side_length):
    matrix = formatted_matrix
    matrix_end = [[0 for column in range(side_length)] for row in range(side_length)]
    for y in range(0, side_length):
        for x in range(0, side_length):
            matrix_end[x][y] = matrix[y][x]
    print_matrix(matrix_end)
            

def print_matrix(matrix):
    for row in matrix:
        print("(" + ", ".join(str(element) for element in row) + ")")

def main(a, b):
    side_length = math.ceil(math.sqrt(len(b)))
    matrix = [b[i:i+side_length] for i in range(0, len(b), side_length)]
    last_row_length = len(matrix[-1])
    if last_row_length < side_length:
        matrix[-1] += [0] * (side_length - last_row_length)
    transpose(matrix, side_length)


if __name__ == "__main__":
    main(a, b)