#!/usr/bin/env python3
##
## EPITECH PROJECT, 2025
## interstonar
## File description:
## interstonar
##

from sys import argv, exit
import os

def print_usage():
    print("USAGE\n\t./interstonar [--global | --local] CONFIG_FILE Px Py Pz Vx Vy Vz")
    print("\nDESCRIPTION")
    print("\t--global  Launch program in global scene mode. The CONFIG_FILE will describe a scene containing massive spherical moving bodies of which at least one is a goal.\n")
    print("\t--local  Launch program in local scene mode. The CONFIG_FILE will describe a scene containing massless motionless shapes.\n")
    print("\tPi\tPosition coordinates of the rock\n")
    print("\tVi  Velocity vector of the rock\n")
    print("\t CONFIG_FILE  TOML configuration file describing a scene.")

def main():
    if len(argv) == 2 and argv[1] == "--help":
        print_usage()
        exit(0)
    if len(argv) != 9:
        print("Error: Invalid number of arguments. Use --help for more information.")
        exit(84)
    if argv[1] != "--global" and argv[1] != "--local":
        print("Error: Invalid argument. Use --help for more information.")
        exit(84)
    if not os.path.isfile(argv[2]):
        print("Error: File not found. Use --help for more information.")
        exit(84)
    try:
        float(argv[3])
        float(argv[4])
        float(argv[5])
        float(argv[6])
        float(argv[7])
        float(argv[8])
    except ValueError:
        print("Error: Invalid argument. Use --help for more information.")
        exit(84)

if __name__ == "__main__":
    main()
