##
## EPITECH PROJECT, 2025
## Makefile
## File description:
## Makefile
##

.SILENT:

SRC	=	StupidUnitConverter.cpp	\

NAME	=	StupidUnitConverter

all:	$(NAME)

$(NAME):
	@g++ $(SRC) -o $(NAME)

clean:
	rm -f $(NAME)

fclean: clean
	rm -f $(NAME)

re:	fclean all