name: test_42sh

on: 
  push:
    branches:
      - '*'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile project
        run: make

      - name: Clean project
        run: make fclean

      - name: Recompile project
        run: make re

      - name: Clean up
        run: make clean

      - name: Check if file exists
        run: |
          if [ -f 42sh ]; then
            echo "File exists"
          else
            echo "File does not exist"
            exit 1
          fi